version: "3"

services:

  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: ${DB_USER:-postgres}
      POSTGRES_PASSWORD: ${DB_PASS:-password}
    volumes:
      - ./db/data:/var/lib/postgresql/data
    ports:
      - 5000:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  keycloak:
    image: bitnami/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: ${KC_ADMIN:-admin}
      KEYCLOAK_ADMIN_PASSWORD: ${KC_ADMIN_PASSWORD:-password}
      KEYCLOAK_DATABASE_HOST: db
      KEYCLOAK_DATABASE_PORT: 5432
      KEYCLOAK_DATABASE_NAME: keycloak_db
      KEYCLOAK_DATABASE_USER: ${DB_USER:-postgres}
      KEYCLOAK_DATABASE_PASSWORD: ${DB_PASS:-password}
      KEYCLOAK_EXTRA_ARGS: --import-realm
    volumes:
      - ./keycloak/:/opt/bitnami/keycloak/data/import
    ports:
      - 8080:8080
    healthcheck: 
      test: ["CMD", "curl", "-f", "http://localhost:8080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    depends_on:
      - db